CC = gcc
CFLAGS = -Wall `pkg-config --cflags gtk+-3.0`
LIBS = `pkg-config --libs gtk+-3.0`

SRC = main.c vibration.c gui.c
OBJ = $(SRC:.c=.o)

all: vibration_control

vibration_control: $(OBJ)
	$(CC) -o $@ $(OBJ) $(LIBS)

clean:
	rm -f vibration_control *.o
